.TH JOBARG_EXEC 1 "17 March 2014"
.if n .ad l
.SH NAME
jobarg_exec \- Jobarranger Jobnet execution utility.
.SH SYNOPSIS
.B jobarg_exec [-hV] -z <server> [-p <port>] -U <user-name> -P <password> -j <jobnet-id> [-t <YYYYMMDDHHMM>] [-E <environment-variables>,...] [-D]
.SH DESCRIPTION
.B jobarg_exec
is a command line utility for executing jobnet to a remote Jobarranger server.
.SS Options
.IP "-z \fI<server>\fR"
Hostname or IP address of Jobarranger server.
.IP "-p \fI<port>\fR"
Specify port number of server trapper running on the server. Default is 10061.
.IP "-U \fI<user-name>\fR"
Specify a user with authority to operate the jobnet.
.IP "-P \fI<password>\fR"
The user password.
.IP "-j \fI<jobnet-id>\fR"
Specify jobnet id as registered in Jobarranger front-end.
.IP "-t \fI<YYYYMMDDHHMM>\fR"
Specify start time of the jobnet.
.IP "-E \fI<environment-variable>,...\fR"
Specify the environment variable name to be registered in the jobnet. You can have multiple contains a comma.
.IP "-D\fR"
Specify the double registration deterrence of time start-up with -t option.
.IP "-h\fR"
Display this help and exit.
.SH "EXIT STATUS"
The exit status is 0 if the jobnet has been started successfully registered.
Exit status is 255 if it fails to register a jobnet or parameter error.
.SH "SEE ALSO"
.BR jobarg_server (8),
.BR jobarg_agentd (8),
.BR jobarg_get (1),
.BR jobarg_joblogput (1),
.BR jobarg_release (1)
.SH AUTHOR
Yasuhiko Kato <kato@fitechforce.co.jp>
