################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../tools/libarchive/libarchive/test/main.c \
../tools/libarchive/libarchive/test/read_open_memory.c \
../tools/libarchive/libarchive/test/test_acl_basic.c \
../tools/libarchive/libarchive/test/test_acl_freebsd.c \
../tools/libarchive/libarchive/test/test_acl_pax.c \
../tools/libarchive/libarchive/test/test_archive_api_feature.c \
../tools/libarchive/libarchive/test/test_bad_fd.c \
../tools/libarchive/libarchive/test/test_compat_bzip2.c \
../tools/libarchive/libarchive/test/test_compat_cpio.c \
../tools/libarchive/libarchive/test/test_compat_gtar.c \
../tools/libarchive/libarchive/test/test_compat_gzip.c \
../tools/libarchive/libarchive/test/test_compat_lzma.c \
../tools/libarchive/libarchive/test/test_compat_solaris_tar_acl.c \
../tools/libarchive/libarchive/test/test_compat_tar_hardlink.c \
../tools/libarchive/libarchive/test/test_compat_xz.c \
../tools/libarchive/libarchive/test/test_compat_zip.c \
../tools/libarchive/libarchive/test/test_empty_write.c \
../tools/libarchive/libarchive/test/test_entry.c \
../tools/libarchive/libarchive/test/test_entry_strmode.c \
../tools/libarchive/libarchive/test/test_extattr_freebsd.c \
../tools/libarchive/libarchive/test/test_fuzz.c \
../tools/libarchive/libarchive/test/test_link_resolver.c \
../tools/libarchive/libarchive/test/test_open_failure.c \
../tools/libarchive/libarchive/test/test_open_fd.c \
../tools/libarchive/libarchive/test/test_open_file.c \
../tools/libarchive/libarchive/test/test_open_filename.c \
../tools/libarchive/libarchive/test/test_pax_filename_encoding.c \
../tools/libarchive/libarchive/test/test_read_compress_program.c \
../tools/libarchive/libarchive/test/test_read_data_large.c \
../tools/libarchive/libarchive/test/test_read_disk.c \
../tools/libarchive/libarchive/test/test_read_disk_entry_from_file.c \
../tools/libarchive/libarchive/test/test_read_extract.c \
../tools/libarchive/libarchive/test/test_read_file_nonexistent.c \
../tools/libarchive/libarchive/test/test_read_format_ar.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_bin.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_bin_Z.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_bin_be.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_bin_bz2.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_bin_gz.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_bin_lzma.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_bin_xz.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_odc.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_svr4_bzip2_rpm.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_svr4_gzip.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_svr4_gzip_rpm.c \
../tools/libarchive/libarchive/test/test_read_format_cpio_svr4c_Z.c \
../tools/libarchive/libarchive/test/test_read_format_empty.c \
../tools/libarchive/libarchive/test/test_read_format_gtar_gz.c \
../tools/libarchive/libarchive/test/test_read_format_gtar_lzma.c \
../tools/libarchive/libarchive/test/test_read_format_gtar_sparse.c \
../tools/libarchive/libarchive/test/test_read_format_iso_Z.c \
../tools/libarchive/libarchive/test/test_read_format_iso_multi_extent.c \
../tools/libarchive/libarchive/test/test_read_format_isojoliet_bz2.c \
../tools/libarchive/libarchive/test/test_read_format_isojoliet_long.c \
../tools/libarchive/libarchive/test/test_read_format_isojoliet_rr.c \
../tools/libarchive/libarchive/test/test_read_format_isorr_bz2.c \
../tools/libarchive/libarchive/test/test_read_format_isorr_ce.c \
../tools/libarchive/libarchive/test/test_read_format_isorr_new_bz2.c \
../tools/libarchive/libarchive/test/test_read_format_isorr_rr_moved.c \
../tools/libarchive/libarchive/test/test_read_format_isozisofs_bz2.c \
../tools/libarchive/libarchive/test/test_read_format_mtree.c \
../tools/libarchive/libarchive/test/test_read_format_pax_bz2.c \
../tools/libarchive/libarchive/test/test_read_format_raw.c \
../tools/libarchive/libarchive/test/test_read_format_tar.c \
../tools/libarchive/libarchive/test/test_read_format_tar_empty_filename.c \
../tools/libarchive/libarchive/test/test_read_format_tbz.c \
../tools/libarchive/libarchive/test/test_read_format_tgz.c \
../tools/libarchive/libarchive/test/test_read_format_tlz.c \
../tools/libarchive/libarchive/test/test_read_format_txz.c \
../tools/libarchive/libarchive/test/test_read_format_tz.c \
../tools/libarchive/libarchive/test/test_read_format_xar.c \
../tools/libarchive/libarchive/test/test_read_format_zip.c \
../tools/libarchive/libarchive/test/test_read_large.c \
../tools/libarchive/libarchive/test/test_read_pax_truncated.c \
../tools/libarchive/libarchive/test/test_read_position.c \
../tools/libarchive/libarchive/test/test_read_truncated.c \
../tools/libarchive/libarchive/test/test_read_uu.c \
../tools/libarchive/libarchive/test/test_tar_filenames.c \
../tools/libarchive/libarchive/test/test_tar_large.c \
../tools/libarchive/libarchive/test/test_ustar_filenames.c \
../tools/libarchive/libarchive/test/test_write_compress.c \
../tools/libarchive/libarchive/test/test_write_compress_bzip2.c \
../tools/libarchive/libarchive/test/test_write_compress_gzip.c \
../tools/libarchive/libarchive/test/test_write_compress_lzma.c \
../tools/libarchive/libarchive/test/test_write_compress_program.c \
../tools/libarchive/libarchive/test/test_write_compress_xz.c \
../tools/libarchive/libarchive/test/test_write_disk.c \
../tools/libarchive/libarchive/test/test_write_disk_failures.c \
../tools/libarchive/libarchive/test/test_write_disk_hardlink.c \
../tools/libarchive/libarchive/test/test_write_disk_perms.c \
../tools/libarchive/libarchive/test/test_write_disk_secure.c \
../tools/libarchive/libarchive/test/test_write_disk_sparse.c \
../tools/libarchive/libarchive/test/test_write_disk_symlink.c \
../tools/libarchive/libarchive/test/test_write_disk_times.c \
../tools/libarchive/libarchive/test/test_write_format_ar.c \
../tools/libarchive/libarchive/test/test_write_format_cpio.c \
../tools/libarchive/libarchive/test/test_write_format_cpio_empty.c \
../tools/libarchive/libarchive/test/test_write_format_cpio_newc.c \
../tools/libarchive/libarchive/test/test_write_format_cpio_odc.c \
../tools/libarchive/libarchive/test/test_write_format_mtree.c \
../tools/libarchive/libarchive/test/test_write_format_pax.c \
../tools/libarchive/libarchive/test/test_write_format_shar_empty.c \
../tools/libarchive/libarchive/test/test_write_format_tar.c \
../tools/libarchive/libarchive/test/test_write_format_tar_empty.c \
../tools/libarchive/libarchive/test/test_write_format_tar_ustar.c \
../tools/libarchive/libarchive/test/test_write_format_zip.c \
../tools/libarchive/libarchive/test/test_write_format_zip_empty.c \
../tools/libarchive/libarchive/test/test_write_format_zip_no_compression.c \
../tools/libarchive/libarchive/test/test_write_open_memory.c 

OBJS += \
./tools/libarchive/libarchive/test/main.o \
./tools/libarchive/libarchive/test/read_open_memory.o \
./tools/libarchive/libarchive/test/test_acl_basic.o \
./tools/libarchive/libarchive/test/test_acl_freebsd.o \
./tools/libarchive/libarchive/test/test_acl_pax.o \
./tools/libarchive/libarchive/test/test_archive_api_feature.o \
./tools/libarchive/libarchive/test/test_bad_fd.o \
./tools/libarchive/libarchive/test/test_compat_bzip2.o \
./tools/libarchive/libarchive/test/test_compat_cpio.o \
./tools/libarchive/libarchive/test/test_compat_gtar.o \
./tools/libarchive/libarchive/test/test_compat_gzip.o \
./tools/libarchive/libarchive/test/test_compat_lzma.o \
./tools/libarchive/libarchive/test/test_compat_solaris_tar_acl.o \
./tools/libarchive/libarchive/test/test_compat_tar_hardlink.o \
./tools/libarchive/libarchive/test/test_compat_xz.o \
./tools/libarchive/libarchive/test/test_compat_zip.o \
./tools/libarchive/libarchive/test/test_empty_write.o \
./tools/libarchive/libarchive/test/test_entry.o \
./tools/libarchive/libarchive/test/test_entry_strmode.o \
./tools/libarchive/libarchive/test/test_extattr_freebsd.o \
./tools/libarchive/libarchive/test/test_fuzz.o \
./tools/libarchive/libarchive/test/test_link_resolver.o \
./tools/libarchive/libarchive/test/test_open_failure.o \
./tools/libarchive/libarchive/test/test_open_fd.o \
./tools/libarchive/libarchive/test/test_open_file.o \
./tools/libarchive/libarchive/test/test_open_filename.o \
./tools/libarchive/libarchive/test/test_pax_filename_encoding.o \
./tools/libarchive/libarchive/test/test_read_compress_program.o \
./tools/libarchive/libarchive/test/test_read_data_large.o \
./tools/libarchive/libarchive/test/test_read_disk.o \
./tools/libarchive/libarchive/test/test_read_disk_entry_from_file.o \
./tools/libarchive/libarchive/test/test_read_extract.o \
./tools/libarchive/libarchive/test/test_read_file_nonexistent.o \
./tools/libarchive/libarchive/test/test_read_format_ar.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_Z.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_be.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_bz2.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_gz.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_lzma.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_xz.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_odc.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_svr4_bzip2_rpm.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_svr4_gzip.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_svr4_gzip_rpm.o \
./tools/libarchive/libarchive/test/test_read_format_cpio_svr4c_Z.o \
./tools/libarchive/libarchive/test/test_read_format_empty.o \
./tools/libarchive/libarchive/test/test_read_format_gtar_gz.o \
./tools/libarchive/libarchive/test/test_read_format_gtar_lzma.o \
./tools/libarchive/libarchive/test/test_read_format_gtar_sparse.o \
./tools/libarchive/libarchive/test/test_read_format_iso_Z.o \
./tools/libarchive/libarchive/test/test_read_format_iso_multi_extent.o \
./tools/libarchive/libarchive/test/test_read_format_isojoliet_bz2.o \
./tools/libarchive/libarchive/test/test_read_format_isojoliet_long.o \
./tools/libarchive/libarchive/test/test_read_format_isojoliet_rr.o \
./tools/libarchive/libarchive/test/test_read_format_isorr_bz2.o \
./tools/libarchive/libarchive/test/test_read_format_isorr_ce.o \
./tools/libarchive/libarchive/test/test_read_format_isorr_new_bz2.o \
./tools/libarchive/libarchive/test/test_read_format_isorr_rr_moved.o \
./tools/libarchive/libarchive/test/test_read_format_isozisofs_bz2.o \
./tools/libarchive/libarchive/test/test_read_format_mtree.o \
./tools/libarchive/libarchive/test/test_read_format_pax_bz2.o \
./tools/libarchive/libarchive/test/test_read_format_raw.o \
./tools/libarchive/libarchive/test/test_read_format_tar.o \
./tools/libarchive/libarchive/test/test_read_format_tar_empty_filename.o \
./tools/libarchive/libarchive/test/test_read_format_tbz.o \
./tools/libarchive/libarchive/test/test_read_format_tgz.o \
./tools/libarchive/libarchive/test/test_read_format_tlz.o \
./tools/libarchive/libarchive/test/test_read_format_txz.o \
./tools/libarchive/libarchive/test/test_read_format_tz.o \
./tools/libarchive/libarchive/test/test_read_format_xar.o \
./tools/libarchive/libarchive/test/test_read_format_zip.o \
./tools/libarchive/libarchive/test/test_read_large.o \
./tools/libarchive/libarchive/test/test_read_pax_truncated.o \
./tools/libarchive/libarchive/test/test_read_position.o \
./tools/libarchive/libarchive/test/test_read_truncated.o \
./tools/libarchive/libarchive/test/test_read_uu.o \
./tools/libarchive/libarchive/test/test_tar_filenames.o \
./tools/libarchive/libarchive/test/test_tar_large.o \
./tools/libarchive/libarchive/test/test_ustar_filenames.o \
./tools/libarchive/libarchive/test/test_write_compress.o \
./tools/libarchive/libarchive/test/test_write_compress_bzip2.o \
./tools/libarchive/libarchive/test/test_write_compress_gzip.o \
./tools/libarchive/libarchive/test/test_write_compress_lzma.o \
./tools/libarchive/libarchive/test/test_write_compress_program.o \
./tools/libarchive/libarchive/test/test_write_compress_xz.o \
./tools/libarchive/libarchive/test/test_write_disk.o \
./tools/libarchive/libarchive/test/test_write_disk_failures.o \
./tools/libarchive/libarchive/test/test_write_disk_hardlink.o \
./tools/libarchive/libarchive/test/test_write_disk_perms.o \
./tools/libarchive/libarchive/test/test_write_disk_secure.o \
./tools/libarchive/libarchive/test/test_write_disk_sparse.o \
./tools/libarchive/libarchive/test/test_write_disk_symlink.o \
./tools/libarchive/libarchive/test/test_write_disk_times.o \
./tools/libarchive/libarchive/test/test_write_format_ar.o \
./tools/libarchive/libarchive/test/test_write_format_cpio.o \
./tools/libarchive/libarchive/test/test_write_format_cpio_empty.o \
./tools/libarchive/libarchive/test/test_write_format_cpio_newc.o \
./tools/libarchive/libarchive/test/test_write_format_cpio_odc.o \
./tools/libarchive/libarchive/test/test_write_format_mtree.o \
./tools/libarchive/libarchive/test/test_write_format_pax.o \
./tools/libarchive/libarchive/test/test_write_format_shar_empty.o \
./tools/libarchive/libarchive/test/test_write_format_tar.o \
./tools/libarchive/libarchive/test/test_write_format_tar_empty.o \
./tools/libarchive/libarchive/test/test_write_format_tar_ustar.o \
./tools/libarchive/libarchive/test/test_write_format_zip.o \
./tools/libarchive/libarchive/test/test_write_format_zip_empty.o \
./tools/libarchive/libarchive/test/test_write_format_zip_no_compression.o \
./tools/libarchive/libarchive/test/test_write_open_memory.o 

C_DEPS += \
./tools/libarchive/libarchive/test/main.d \
./tools/libarchive/libarchive/test/read_open_memory.d \
./tools/libarchive/libarchive/test/test_acl_basic.d \
./tools/libarchive/libarchive/test/test_acl_freebsd.d \
./tools/libarchive/libarchive/test/test_acl_pax.d \
./tools/libarchive/libarchive/test/test_archive_api_feature.d \
./tools/libarchive/libarchive/test/test_bad_fd.d \
./tools/libarchive/libarchive/test/test_compat_bzip2.d \
./tools/libarchive/libarchive/test/test_compat_cpio.d \
./tools/libarchive/libarchive/test/test_compat_gtar.d \
./tools/libarchive/libarchive/test/test_compat_gzip.d \
./tools/libarchive/libarchive/test/test_compat_lzma.d \
./tools/libarchive/libarchive/test/test_compat_solaris_tar_acl.d \
./tools/libarchive/libarchive/test/test_compat_tar_hardlink.d \
./tools/libarchive/libarchive/test/test_compat_xz.d \
./tools/libarchive/libarchive/test/test_compat_zip.d \
./tools/libarchive/libarchive/test/test_empty_write.d \
./tools/libarchive/libarchive/test/test_entry.d \
./tools/libarchive/libarchive/test/test_entry_strmode.d \
./tools/libarchive/libarchive/test/test_extattr_freebsd.d \
./tools/libarchive/libarchive/test/test_fuzz.d \
./tools/libarchive/libarchive/test/test_link_resolver.d \
./tools/libarchive/libarchive/test/test_open_failure.d \
./tools/libarchive/libarchive/test/test_open_fd.d \
./tools/libarchive/libarchive/test/test_open_file.d \
./tools/libarchive/libarchive/test/test_open_filename.d \
./tools/libarchive/libarchive/test/test_pax_filename_encoding.d \
./tools/libarchive/libarchive/test/test_read_compress_program.d \
./tools/libarchive/libarchive/test/test_read_data_large.d \
./tools/libarchive/libarchive/test/test_read_disk.d \
./tools/libarchive/libarchive/test/test_read_disk_entry_from_file.d \
./tools/libarchive/libarchive/test/test_read_extract.d \
./tools/libarchive/libarchive/test/test_read_file_nonexistent.d \
./tools/libarchive/libarchive/test/test_read_format_ar.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_Z.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_be.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_bz2.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_gz.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_lzma.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_bin_xz.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_odc.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_svr4_bzip2_rpm.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_svr4_gzip.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_svr4_gzip_rpm.d \
./tools/libarchive/libarchive/test/test_read_format_cpio_svr4c_Z.d \
./tools/libarchive/libarchive/test/test_read_format_empty.d \
./tools/libarchive/libarchive/test/test_read_format_gtar_gz.d \
./tools/libarchive/libarchive/test/test_read_format_gtar_lzma.d \
./tools/libarchive/libarchive/test/test_read_format_gtar_sparse.d \
./tools/libarchive/libarchive/test/test_read_format_iso_Z.d \
./tools/libarchive/libarchive/test/test_read_format_iso_multi_extent.d \
./tools/libarchive/libarchive/test/test_read_format_isojoliet_bz2.d \
./tools/libarchive/libarchive/test/test_read_format_isojoliet_long.d \
./tools/libarchive/libarchive/test/test_read_format_isojoliet_rr.d \
./tools/libarchive/libarchive/test/test_read_format_isorr_bz2.d \
./tools/libarchive/libarchive/test/test_read_format_isorr_ce.d \
./tools/libarchive/libarchive/test/test_read_format_isorr_new_bz2.d \
./tools/libarchive/libarchive/test/test_read_format_isorr_rr_moved.d \
./tools/libarchive/libarchive/test/test_read_format_isozisofs_bz2.d \
./tools/libarchive/libarchive/test/test_read_format_mtree.d \
./tools/libarchive/libarchive/test/test_read_format_pax_bz2.d \
./tools/libarchive/libarchive/test/test_read_format_raw.d \
./tools/libarchive/libarchive/test/test_read_format_tar.d \
./tools/libarchive/libarchive/test/test_read_format_tar_empty_filename.d \
./tools/libarchive/libarchive/test/test_read_format_tbz.d \
./tools/libarchive/libarchive/test/test_read_format_tgz.d \
./tools/libarchive/libarchive/test/test_read_format_tlz.d \
./tools/libarchive/libarchive/test/test_read_format_txz.d \
./tools/libarchive/libarchive/test/test_read_format_tz.d \
./tools/libarchive/libarchive/test/test_read_format_xar.d \
./tools/libarchive/libarchive/test/test_read_format_zip.d \
./tools/libarchive/libarchive/test/test_read_large.d \
./tools/libarchive/libarchive/test/test_read_pax_truncated.d \
./tools/libarchive/libarchive/test/test_read_position.d \
./tools/libarchive/libarchive/test/test_read_truncated.d \
./tools/libarchive/libarchive/test/test_read_uu.d \
./tools/libarchive/libarchive/test/test_tar_filenames.d \
./tools/libarchive/libarchive/test/test_tar_large.d \
./tools/libarchive/libarchive/test/test_ustar_filenames.d \
./tools/libarchive/libarchive/test/test_write_compress.d \
./tools/libarchive/libarchive/test/test_write_compress_bzip2.d \
./tools/libarchive/libarchive/test/test_write_compress_gzip.d \
./tools/libarchive/libarchive/test/test_write_compress_lzma.d \
./tools/libarchive/libarchive/test/test_write_compress_program.d \
./tools/libarchive/libarchive/test/test_write_compress_xz.d \
./tools/libarchive/libarchive/test/test_write_disk.d \
./tools/libarchive/libarchive/test/test_write_disk_failures.d \
./tools/libarchive/libarchive/test/test_write_disk_hardlink.d \
./tools/libarchive/libarchive/test/test_write_disk_perms.d \
./tools/libarchive/libarchive/test/test_write_disk_secure.d \
./tools/libarchive/libarchive/test/test_write_disk_sparse.d \
./tools/libarchive/libarchive/test/test_write_disk_symlink.d \
./tools/libarchive/libarchive/test/test_write_disk_times.d \
./tools/libarchive/libarchive/test/test_write_format_ar.d \
./tools/libarchive/libarchive/test/test_write_format_cpio.d \
./tools/libarchive/libarchive/test/test_write_format_cpio_empty.d \
./tools/libarchive/libarchive/test/test_write_format_cpio_newc.d \
./tools/libarchive/libarchive/test/test_write_format_cpio_odc.d \
./tools/libarchive/libarchive/test/test_write_format_mtree.d \
./tools/libarchive/libarchive/test/test_write_format_pax.d \
./tools/libarchive/libarchive/test/test_write_format_shar_empty.d \
./tools/libarchive/libarchive/test/test_write_format_tar.d \
./tools/libarchive/libarchive/test/test_write_format_tar_empty.d \
./tools/libarchive/libarchive/test/test_write_format_tar_ustar.d \
./tools/libarchive/libarchive/test/test_write_format_zip.d \
./tools/libarchive/libarchive/test/test_write_format_zip_empty.d \
./tools/libarchive/libarchive/test/test_write_format_zip_no_compression.d \
./tools/libarchive/libarchive/test/test_write_open_memory.d 


# Each subdirectory must supply rules for building sources it contributes
tools/libarchive/libarchive/test/%.o: ../tools/libarchive/libarchive/test/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


