<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Rakit\\Validation\\' => array($vendorDir . '/rakit/validation/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'League\\Fractal\\' => array($vendorDir . '/league/fractal/src'),
    'FastRoute\\' => array($vendorDir . '/nikic/fast-route/src'),
    'EllipseSynergie\\ApiResponse\\Tests\\' => array($vendorDir . '/ellipsesynergie/api-response/tests'),
    'EllipseSynergie\\ApiResponse\\' => array($vendorDir . '/ellipsesynergie/api-response/src'),
    'App\\' => array($baseDir . '/app'),
);
